import TypingText from "@/components/common/TypingText";

type Props = {
  response: string;
};

export default function AIResponse({ response }: Props) {
  if (!response) {
    return (
      <div className="mt-8 rounded-2xl border border-dashed border-cyan-500/30 bg-[#111827] p-8 text-center">

        <div className="text-6xl">🤖</div>

        <h2 className="mt-4 text-2xl font-bold text-cyan-400">
          AI Operations Plan
        </h2>

        <p className="mt-3 text-gray-400">
          Generate an AI operations plan to receive recommendations,
          resources and public announcements.
        </p>

      </div>
    );
  }

  let data: any = null;

  try {
    data = JSON.parse(response);
  } catch {
    data = null;
  }

  if (!data) {
    return (
      <div className="mt-8 rounded-2xl border border-cyan-500/30 bg-[#111827] p-6 shadow-xl">

        <h2 className="mb-4 text-2xl font-bold text-cyan-400">
          AI Operations Plan
        </h2>

        <TypingText text={response} />

      </div>
    );
  }

  const resources = data.resources ?? {
    securityTeams: "-",
    medicalTeams: "-",
    volunteers: "-",
    policeUnits: "-",
  };

  const actionPlan = Array.isArray(data.actionPlan)
    ? data.actionPlan
    : [];

  const riskLevel = data.riskLevel ?? "Unknown";
  const confidence = data.confidence ?? "--";
  const estimatedResolution =
    data.estimatedResolution ?? "--";

  const publicAnnouncement =
    data.publicAnnouncement ??
    "No public announcement generated.";

  return (
    <div className="mt-8 rounded-2xl border border-cyan-500/30 bg-[#111827] p-6 shadow-xl space-y-8 animate-in fade-in duration-500">

      <div className="flex items-center justify-between">

        <h2 className="text-2xl font-bold text-cyan-400">
          AI Operations Plan
        </h2>

        <span className="rounded-full bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-300">
          Generated by VenueVerse AI
        </span>

      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

        <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-5 transition hover:scale-105">

          <p className="text-gray-400">
            🚨 Risk Level
          </p>

          <p className="mt-3 text-3xl font-bold text-red-400">
            {riskLevel}
          </p>

        </div>

        <div className="rounded-xl border border-green-500/20 bg-green-500/10 p-5 transition hover:scale-105">

          <p className="text-gray-400">
            🎯 AI Confidence
          </p>

          <p className="mt-3 text-3xl font-bold text-green-400">
            {confidence}
          </p>

        </div>

        <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/10 p-5 transition hover:scale-105">

          <p className="text-gray-400">
            ⏱ Resolution ETA
          </p>

          <p className="mt-3 text-3xl font-bold text-yellow-400">
            {estimatedResolution}
          </p>

        </div>

      </div>

      <div>

        <h3 className="mb-4 text-xl font-semibold text-cyan-400">
          👮 Resources Required
        </h3>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">

          {[
            ["👮", resources.securityTeams, "Security"],
            ["🚑", resources.medicalTeams, "Medical"],
            ["🙋", resources.volunteers, "Volunteers"],
            ["🚔", resources.policeUnits, "Police"],
          ].map(([icon, value, label]) => (

            <div
              key={label}
              className="rounded-xl bg-[#1F2937] p-5 text-center transition hover:scale-105"
            >

              <p className="text-3xl">
                {icon}
              </p>

              <p className="mt-2 text-3xl font-bold">
                {value}
              </p>

              <p className="mt-1 text-sm text-gray-400">
                {label}
              </p>

            </div>

          ))}

        </div>

      </div>

      <div>

        <h3 className="mb-4 text-xl font-semibold text-cyan-400">
          📋 AI Action Plan
        </h3>

        {actionPlan.length ? (

          <div className="space-y-3">

            {actionPlan.map((step: string, index: number) => (

              <div
                key={index}
                className="rounded-xl bg-[#1F2937] p-4"
              >
                <span className="font-semibold text-cyan-400">
                  Step {index + 1}
                </span>

                <div className="mt-2">
                  <TypingText text={step} speed={12} />
                </div>

              </div>

            ))}

          </div>

        ) : (

          <div className="rounded-xl bg-[#1F2937] p-5 text-gray-400">
            No action plan generated.
          </div>

        )}

      </div>

      <div>

        <h3 className="mb-4 text-xl font-semibold text-cyan-400">
          📢 Public Announcement
        </h3>

        <div className="rounded-xl bg-[#1F2937] p-5">

          <TypingText
            text={publicAnnouncement}
            speed={14}
          />

        </div>

      </div>

    </div>
  );
}